### ISSUE TITLE
user-can-view-residents

### ISSUE THREAD

**Issue by matt-cha** [matt-cha/villager-tunes#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view village that has the list and a background of the island

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1084" alt="Screen Shot 2023-01-10 at 3 34 01 PM" src="https://user-images.githubusercontent.com/113474295/211684214-ed446d08-c077-4243-8211-17e1f861e477.png">
<img width="432" alt="Screen Shot 2023-01-10 at 3 33 53 PM" src="https://user-images.githubusercontent.com/113474295/211684220-10cc32b4-4e1d-4085-899b-773990c997dd.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a new view for home page that will show all residents added
- [x] Add a click event to the home button that will take user to the new page
- [x] Create dummy entries for desktop and mobile to feature 2 residents and 10 residents
- [x] Define a function for renderVillage that will generate a DOM tree for each villager in the liked array of the data object
- [x]  Rotate through the residents automatically every three seconds for mobile
- [x] Create a modal that displays the village card information when a villager is clicked
- [x] Add an X icon to close the modal
- [x] Create a function viewSwap to change views when searching or clicking the home button
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
